export const FETCH_DEMO_DATA = 'FETCH_DEMO_DATA';
export const FETCH_DEMO_DATA_SUCCESS = 'FETCH_DEMO_DATA_SUCCESS';
export const FETCH_DEMO_DATA_ERROR = 'FETCH_DEMO_DATA_ERROR';

export const SET_PROCESS_ENV = 'SET_PROCESS_ENV';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_QUOTES = 'FETCH_QUOTES';
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS';
export const FETCH_QUOTES_ERROR = 'FETCH_QUOTES_ERROR';

export const DELETE_QUOTE = 'DELETE_QUOTE';
export const DELETE_QUOTE_SUCCESS = 'DELETE_QUOTE_SUCCESS';
export const DELETE_QUOTE_ERROR = 'DELETE_QUOTE_ERROR';
