export const FETCH_DEMO_DATA = 'FETCH_DEMO_DATA';
export const FETCH_DEMO_DATA_SUCCESS = 'FETCH_DEMO_DATA_SUCCESS';
export const FETCH_DEMO_DATA_ERROR = 'FETCH_DEMO_DATA_ERROR';

export const SET_PROCESS_ENV = 'SET_PROCESS_ENV';
